name: Ratchet verify
on:
  pull_request:
    paths: ['.github/workflows/**']
jobs:
  ratchet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # ratchet:actions/checkout@v4
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # ratchet:actions/setup-go@v5
        with:
          go-version: stable
      - name: Install ratchet
        run: |
          go install github.com/sethvargo/ratchet@v0.11.3
          ratchet --version
      - name: Verify pinned SHAs
        run: ratchet lint .github/workflows/*.yml
